// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zipcode/app/restapi"
	"zipcode/data/repositories"
	"zipcode/domain/usecase"
	"zipcode/infrastructure/server"
	"zipcode/presentation/api"
)

// Injectors from di_restapi.go:

func InitializeRestApi() server.Server {
	zipCodeRepository := repositories.NewFileRepository()
	addressFinder := usecase.NewAddressFinder(zipCodeRepository)
	apiController := api.NewApiController(addressFinder)
	serverServer := restapi.NewApiServer(apiController)
	return serverServer
}
