// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphmodel

type Address struct {
	ID           string `json:"id"`
	Zipcode      string `json:"zipcode"`
	City         *City  `json:"city"`
	Townname     string `json:"townname"`
	Townnamekana string `json:"townnamekana"`
}

type City struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Namekana   string      `json:"namekana"`
	Prefecture *Prefecture `json:"prefecture"`
}

type Prefecture struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Nameroman string `json:"nameroman"`
}
